version: '3.8'

services:
  # Blue 환경
  app-blue:
    image: ${DOCKER_USERNAME:-your_username}/image-change:blue-${IMAGE_TAG:-latest}
    ports:
      - '3001:80'
    networks:
      - app-network
    restart: unless-stopped

  # Green 환경
  app-green:
    image: ${DOCKER_USERNAME:-your_username}/image-change:green-${IMAGE_TAG:-latest}
    ports:
      - '3002:80'
    networks:
      - app-network
    restart: unless-stopped

  # Load Balancer (Nginx)
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx-simple.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      - app-blue
      - app-green

networks:
  app-network:
    driver: bridge
